name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: docker/setup-buildx-action@v4
    - uses: ./.github/actions
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      with:
        tags: latest
        platform: linux/amd64

  image-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/r')
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: image-release-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: wodby/images/.github/actions/image-release@412e2d9ce29c41835ff653b0945bba72eabd9efb
